name: AngeAI
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytest
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - spacy
  - nltk
  - beautifulsoup4
  - lxml
  - requests
  - pydantic
  - tqdm
  - pillow
  - pip:
      - torch
      - torchvision
      - torchaudio
      - tensorflow
      - paddlenlp
      - pymongo
      - keyring
      - regex
      - ddgs
      - iso639
      - blake3
      - easyocr
      - pymupdf
      - pdfplumber
      - opencv-python
      - fastapi
      - uvicorn