# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Integration Tests
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Conda env
        uses: actions/cache@v4
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('conda_environment.yml') }}

      - name: Set up Miniforge (Conda)
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          # Points to your uploaded file
          environment-file: conda_environment.yml
          # Ensures the environment name matches the file (AngeAI)
          activate-environment: AngeAI
          # Recommended: uses Mamba for much faster dependency resolution
          use-mamba: true
          # Crucial for caching to work correctly
          auto-activate-base: false

      - name: Verify Environment
        shell: bash -el {0}
        run: |
          conda info
          conda list

      - name: Run Tests
        # 'shell: bash -el {0}' is required to keep the conda env active in this step
        shell: bash -el {0}
        run: |
          pytest

